version: '3'
services:
  web:
    restart: always
    networks:
      - taskmgr
    image: nginx:alpine
    ports:
      - "8082:80"
    links:
      - app
      - api
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    restart: always
    networks:
      - taskmgr
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run serve

  api:
    restart: always
    networks:
      - development_development
      - taskmgr
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - ./app/vendor

networks:
  taskmgr:
    driver: bridge
  development_development:
    external: true
